// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRK1QJ6qE158robBNxzq2Y6Ct5m7COsUk',
    appId: '1:635066271381:web:b9cefdb86dec1f0503fd9c',
    messagingSenderId: '635066271381',
    projectId: 'weatherapp-c6583',
    authDomain: 'weatherapp-c6583.firebaseapp.com',
    storageBucket: 'weatherapp-c6583.appspot.com',
    measurementId: 'G-3K0Y3N01BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChd4d_mvIYoEzfH0Jwto9W4iGiGBl9iig',
    appId: '1:635066271381:android:f7b5ed997268ab8303fd9c',
    messagingSenderId: '635066271381',
    projectId: 'weatherapp-c6583',
    storageBucket: 'weatherapp-c6583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqqLvKIZOanQIV25rS_Tnl8TZqsEz8Vx4',
    appId: '1:635066271381:ios:727417e0baf724cf03fd9c',
    messagingSenderId: '635066271381',
    projectId: 'weatherapp-c6583',
    storageBucket: 'weatherapp-c6583.appspot.com',
    iosBundleId: 'com.example.weatherapp',
  );
}
